version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "4173:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
